### ISSUE TITLE
关于发送图片,图片链接为外网链接

### ISSUE THREAD

**Issue by kumaCode250** [ksust/HTTP--API#13]
当使用[ksust,image:pic=图片地址]发送图片时,由于链接为外网链接,导致无法获取图片而报错ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
是否能够自己设置代理,或能否发送本地图片?

**Comment by ksust** [comment]
解决方法：目前可以使用不同平台(例如酷Q、QQLight等)的特定图片标签发送本地图片。   
ksust作为屏蔽不同平台差异的统一标签，当时的定位是网络操作，后续也应该会允许一些资源本地操作

**Comment by kumaCode250** [comment]
好的,经过测试,目前可以先把图片爬取到本地,再通过不同平台的特定图片标签发送.
虽然多了一个步骤,但至少已经达到了目的
如果可以的话,是否可以考虑像Python的requests一样,可以设置代理?

**Comment by ksust** [comment]
实际上，可以通过搭建一个本地http server方式来发送本地图片
