### ISSUE TITLE
使用建议

### ISSUE THREAD

**Issue by q461625091** [ksust/HTTP--API#3]
1. 文档上有一个219事件没写出来。
219事件代表的是 邀请入群不需要管理员同意，直接入群的事件。
215 是 邀请入群，对方已同意，管理员未同意的事件。

2. 建议当PHP返回的消息为空时，插件不要显示解析失败。这让小白总以为自己炸了

3. 增加一个取QQ消息中的图片的链接。

4. 禁言这种操作能不能直接用“提交功能”，解析php返回的信息操作。"推送功能"这种操作很多人玩不来。

5. 啥时候可以通过推送发送json和xml

**Comment by ksust** [comment]
已经包含
