### ISSUE TITLE
怎么获取机器人Cookie

### ISSUE THREAD

**Issue by ChinaBygones** [ksust/HTTP--API#8]
怎么获取机器人Cookie

**Comment by ksust** [comment]
你看一下有接口没，没有的话下一版本更新增加

**Comment by ChinaBygones** [comment]
没有，或者您告诉我一下dll接口中获取cookie接口，我可以自己封装，或者抽空您更新一下

**Comment by ksust** [comment]
你看一下相关事件ID然后可以尝试使用sendMsg通过事件ID调用，不行的话则需要等待我这边更新

**Comment by ksust** [comment]
为了安全，目前版本没有提供。后续版本视具体需求提供，主要问题是使用插件的人担心安全问题，所以一直没有加入取cookie接口
